### ISSUE TITLE
Unable to use on Windows Platform 

### ISSUE THREAD

**Issue by H4ckOm** [jspw/cp-tool#1]
I have installed module via `python -m pip install cp-tool` while If I try to use it as mentioned using command `cp-tool` It's giving me an error. I'm using windows machine. 
```
The term 'cp-tool' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again
```

**Comment by jspw** [comment]
@H4ckOm  Are you sure you have installed python3 ? I think it's working fine in my windows machine.
Check that you have python3 installed using  `ptyhon --version`  in your cmd. 
![Screenshot (27)](https://user-images.githubusercontent.com/40170955/104600167-d8632900-56a2-11eb-8dc2-1655b70d75f5.png)

**Comment by jspw** [comment]
@H4ckOm  Please make sure you have selected  **add path** (at the bottom) while installing python in windows machine.

**Comment by H4ckOm** [comment]
Hey I'm still unable to use it. can you please tell me how to do check add path option too?
![Screenshot (832)](https://user-images.githubusercontent.com/54940385/104682936-e608c500-571b-11eb-8dea-9feeac55e30c.png)

**Comment by jspw** [comment]
- Go to `Edit the system environment variable` (you can search in your pc) ![](https://github.com/jspw/VS-Code-Config/raw/master/images/search%20system%20enbironment.png)
- go to Environment variables ![](https://github.com/jspw/VS-Code-Config/raw/master/images/environment%20variable.png)
- Go to system varibale and click on path ![](https://github.com/jspw/VS-Code-Config/raw/master/images/path%20edit%20and%20add%20new.png)
- click edit
- select new
- paste the link where you have installed python (for me it's `C:\Users\jspw\AppData\Local\Programs\Python\Python39\`)
- select ok and ok ....

Then use `python --version`  to check if you have successfully installed python and it will show its version.
And try installing `cp-tool` :D

**Comment by jspw** [comment]
@H4ckOm  if still you are not abe to set path  thn just uinstall the current python and install newly and this time make sure you select **add path** which can be find at the bottom center of the installation wizard.

**Comment by jspw** [comment]
I think you havent added path in the system environment and  this issue is not related to **cp-tool* and i am closing this.
