### ISSUE TITLE
It is not added to path

### ISSUE THREAD

**Issue by HatemSaadallah** [jspw/cp-tool#4]
Instructions about how to use it after installation not clear on linux. 

I can't find it in path.

**Comment by jspw** [comment]
Did you mean using `cp-tool` command showing `I can't find it in path` ? Can you show me a screenshot ? @HatemSaadallah

**Comment by HatemSaadallah** [comment]
I had to use sudo when installing using pip. It doesn't work when using the flag --user. 

Thanks, it's working wonderfully!
